baseURL = "https://goofy-ptolemy-49e824.netlify.com/"
languageCode = "en-gb"
title = "Adam Rutter"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT = "true"

[blackfriday]
  hrefTargetBlank = true
