backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'src/img'
public_folder: '/img'
collections:
  - label: 'About Me'
    name: 'about-me'
    editor:
      preview: false
    files:
      - label: 'Who I Am'
        name: 'who-i-am'
        file: 'content/home/about-me/who-i-am/section-00.md'
        fields:
          - { label: 'Heading', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Image alt text', name: 'imageAlt', widget: 'string' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'What I Do (1)'
        name: 'what-i-do-1'
        file: 'content/home/about-me/what-i-do/section-00.md'
        fields:
          - { label: 'Heading', name: 'title', widget: 'string' }
          - { label: 'Order', name: 'weight', widget: 'number' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'What I Do (2)'
        name: 'what-i-do-2'
        file: 'content/home/about-me/what-i-do/section-01.md'
        fields:
          - { label: 'Heading', name: 'title', widget: 'string' }
          - { label: 'Order', name: 'weight', widget: 'number' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
      - label: 'How I Do It'
        name: 'how-i-do-it'
        file: 'content/home/about-me/how-i-do-it/section-00.md'
        fields:
          - { label: 'Heading', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
  - label: 'My Work'
    label_singular: 'Project'
    name: 'my-work'
    editor:
      preview: false
    filter: { field: 'editor', value: true }
    folder: 'content/home/my-work'
    create: true
    fields:
      - { label: 'Heading', name: 'title', widget: 'string' }
      - { label: 'Markup', name: 'markup', widget: 'hidden', default: 'mmark' }
      - { label: 'Editor', name: 'editor', widget: 'hidden', default: 'true' }
      - { label: 'Order', name: 'weight', widget: 'number', required: false }
      - { label: 'Desktop image', name: 'desktopImage', widget: 'image' }
      - { label: 'Mobile image', name: 'mobileImage', widget: 'image', required: false }
      - { label: 'Web link', name: 'webLink', widget: 'string', required: false }
      - { label: 'GitHub link', name: 'githubLink', widget: 'string', required: false }
      - { label: 'Testitmonial', name: 'testimonial', widget: 'markdown', required: false }
      - { label: 'Testimonial author', name: 'testimonialAuthor', widget: 'string', required: false }
      - { label: 'Project description', name: 'body', widget: 'markdown'}
  - label: 'Let''s Talk'
    name: 'lets-talk'
    editor:
      preview: false
    files:
      - label: 'Let''s Talk'
        name: 'lets-talk'
        file: 'content/home/lets-talk/section-00.md'
        fields:
          - { label: 'Heading', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'body', widget: 'markdown' }
  - label: 'Description'
    name: 'description'
    editor:
      preview: false
    files:
      - label: 'Description'
        name: 'description'
        file: 'content/_index.md'
        fields:
          - { label: 'Description', name: 'description', widget: 'string', hint: 'For SEO; displayed in search rankings' }
