backend:
  name: git-gateway
  branch: netlify-cms

publish_mode: editorial_workflow

media_folder: "src/img"
public_folder: "/img"

collections:
  - label: "what-i-do"
    name: "What I Do"
    folder: "home/about-me/what-i-do"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
