backend:
  name: git-gateway
  branch: netlify-cms

publish_mode: editorial_workflow

media_folder: "src/img"
public_folder: "/img"

collections:
  - label: "About Me"
    name: "about-me"
    editor:
      preview: false
    files:
      - label: "What I Do 1"
        name: "what-i-do"
        file: "content/home/about-me/what-i-do/section-00.md"
        create: false
        fields:
          - {label: "Heading", name: "title", widget: "string"}
          - {label: "Order", name: "weight", widget: "number"}
          - {label: "Content", name: "body", widget: "markdown"}
